### ISSUE TITLE
Opis projektu

### ISSUE THREAD

**Issue by P3Vu** [P3Vu/Projekt-grupowy#3]
Temat projektu : Rozproszony system inteligentnego oświetlenia ulicznego

**OPIS**
Chciałbym żeby każdy z nas zaproponował swój własny opis, który w szczególności dotyczyłby jego części. Wstępnie ustaliliśmy następujący podział : 
- Paweł Wojciechowski ( Hardware )
- Luiza Błaszczak ( Firmware )
- Anita Kaszuba ( Web App / Firmware ) 

Anicie dorzuciłem firmware bo nie wiemy jeszcze w jakim kierunku pójdzie aplikacja.
Ogólnie rzecz biorąc chciałbym aby każdy dodał coś od siebie. Gromadzimy materiały, wstawiamy w issue od literatury i proponujemy poniżej. 

Dla mnie będzie to przykładowo : 
- projekt i wykonanie obwodu drukowanego umożliwiającego komunikację w wybrana stacją oświetlenia ulicznego

Możecie to zrobić w formie punktów bądź opisowo. Kiedy każdy z nas da coś od siebie przejdziemy do pt.2 czyli zsumowanie wszystkich naszych myśli i wywołanie wersji finałowej.

**Deadline : 25.03.2020 15:00 pt.1 - Wstępne pomysły** 
**Deadline : 25.03.2020 22:00 pt.2 - Wersja końcowa**

**Comment by Luiza2** [comment]
Celem projektu jest opracowanie inteligentnego systemu sterowania światłami ulicznymi. Dedykowany system wbudowany ma wykorzystywać  komunikację bezprzewodową do wymiany informacji z komputerem PC, na który zostanie napisana aplikacja do sterowania oświetleniem i analizy danych. Wynikiem projektu będzie działające urządzenie prototypowe.

Zadania do wykonania:
1. Zapoznanie się ze sposobami komunikacji bezprzewodowej.
2. Opracowanie koncepcji systemu rozproszonego.
3. Projekt i wykonanie obwodu drukowanego.
4. Napisanie oprogramowania na mikrokontroler.
5. Wykonanie aplikacji (PC/smartfon).
6. Testowanie układu.

Literatura:
1. Paprocki K., Mikrokontrolery STM32 w praktyce, Wyd. BTC, 2009
2. Embedded Software: Know it all  J. Labrosse, J. Ganssle, R. Oshana, C. Walls, K. Curtis, J. Andrews, D. Katz, R. Gentile, K. Hyder, B. Perrin

**Comment by P3Vu** [comment]
Celem projektu jest realizacja systemu, który z wykorzystaniem dostępnych technologii komunikacji bezprzewodowej lub przewodowej umożliwiałby m.in. pomiar, analizę oraz sterowanie systemem oświetlenia ulicznego. 

Wykonanie systemu przewiduje takie zadania jak :

   1. Wyselekcjonowanie odpowiedniego standardu komunikacji umożliwiającego łączenie się poszczególnych stacji
   2. Wybranie modułu deweloperskiego, który umożliwiałby przeprowadzenie wstępnych testów
   3. Zapoznanie się z dostępnymi technologiami, konstrukcją oraz pomiarami parametrów lamp wykorzystywanych w oświetleniu ulicznym
   4. Wykonanie obwodu drukowanego oraz oprogramowania umożliwiającego sterowanie, pomiar aktualnych parametrów oraz komunikację ze stacją oświetlenia ulicznego
   5. Wykonanie aplikacji / oprogramowania umożliwiającego integrację danych pochodzących z poszczególnych stacji i ich dystrybucję np. w postaci strony www lub aplikacji webowej. Komunikacja zakłada prace dwukierunkową co stwarza możliwości sterowania w sposób zewnętrzny. 
   6. Przeprowadzenie testów systemu w warunkach zewnętrznych

**Comment by P3Vu** [comment]
Wersja finalna :

Celem projektu jest opracowanie inteligentnego systemu sterowania światłami ulicznymi, który z wykorzystaniem dostępnych technologii komunikacji bezprzewodowej oraz przewodowej umożliwiałby m.in. pomiar, analizę oraz sterowanie systemem oświetlenia ulicznego. Dedykowany system wbudowany ma przekazywać dane ze stacji do aplikacji, która umożliwiać ma dalsze ich przetwarzanie i analizę.

Zadania do wykonania 
1. Zapoznanie się oraz wyselekcjonowanie odpowiedniego standardu komunikacji umożliwiającego połączenie systemu
2. Opracowanie koncepcji systemu rozproszonego.
3. Zapoznanie się z dostępnymi technologiami, konstrukcją oraz pomiarami parametrów lamp wykorzystywanych w oświetleniu ulicznym.
4. Projekt, wykonanie i oprogramowanie systemu wbudowanego.
5. Wykonanie aplikacji umożliwiającej integrację danych pochodzących z poszczególnych stacji np. w postaci serwera www lub aplikacji webowej.
6.  Przeprowadzenie testów systemu.

Literatura:
1. Paprocki K., Mikrokontrolery STM32 w praktyce, Wyd. BTC, 2009
2. Embedded Software: Know it all  J. Labrosse, J. Ganssle, R. Oshana, C. Walls, K. Curtis, J. Andrews, D. Katz, R. Gentile, K. Hyder, B. Perrin

**Comment by P3Vu** [comment]
Zatwierdzone przez opiekuna. Zamykam.
